name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Telepítés
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Kód letöltése
        uses: actions/checkout@v4

      - name: 📁 Fájlok másolása SFTP-vel
        uses: presslabs/gaction-sftp-sync@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          dir: '.'
