name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Telepítés
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Kód letöltése
        uses: actions/checkout@v4

      - name: 📁 Fájlok másolása SFTP-vel
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          remote_path: '/site/'
          local_path: './*'
